#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/yinaw/CODE/nrn-7.4/bin"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/yinaw/CODE/nrn-7.4/bin/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/yinaw/braintv/simulator/bionet/components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
